// recipe_data.dart
import 'recipe.dart';
import 'comment.dart';

class RecipeData {
  static final List<Recipe> recipes = [
    Recipe(
      name: 'Spaghetti Bolognese',
      tags: ['Easy', 'Italian', 'Pasta', 'Non-Vegetarian'],
      imageUrl: 'https://biodharma.pt/wp-content/uploads/2020/05/esprguete-%C3%A0-bolonhesa-1.jpg',
      description: 'A classic Italian pasta dish with a rich, savory meat sauce.',
      servings: 2,
      defaultServings: 2,
      ingredients: [
        Ingredient(name: 'Spaghetti', baseQuantity: 200, unit: 'grams'),
        Ingredient(name: 'Ground beef', baseQuantity: 150, unit: 'grams'),
        Ingredient(name: 'Tomato sauce', baseQuantity: 100, unit: 'ml'),
        Ingredient(name: 'Garlic', baseQuantity: 2, unit: 'cloves'),
        Ingredient(name: 'Onion', baseQuantity: 1, unit: 'medium'),
        Ingredient(name: 'Olive oil', baseQuantity: 1, unit: 'tbsp'),
        Ingredient(name: 'Salt', baseQuantity: 0.5, unit: 'tsp'),
        Ingredient(name: 'Pepper', baseQuantity: 0.25, unit: 'tsp'),
      ],
      steps: [
        RecipeStep(description: 'Boil the spaghetti according to package instructions.', timer: 10),
        RecipeStep(description: 'Heat olive oil in a pan and sauté garlic and onion.', timer: 5),
        RecipeStep(description: 'Add ground beef and cook until browned.', timer: 7),
        RecipeStep(description: 'Add tomato sauce and simmer.', timer: 15),
        RecipeStep(description: 'Season with salt and pepper to taste.'),
        RecipeStep(description: 'Serve sauce over spaghetti.'),
      ],
      comments: [
        Comment(username: 'Alice', rating: 5, text: 'Absolutely delicious! The whole family loved it.'),
        Comment(username: 'Bob', rating: 4, text: 'Great recipe, but I added some basil for extra flavor.'),
        Comment(username: 'Charlie', rating: 3, text: 'Pretty good, but a bit too salty for my taste.'),
      ],
    ),
    Recipe(
      name: 'Duck Rice',
      tags: ['Medium', 'Portuguese', 'Non-Vegetarian', 'Rice'],
      imageUrl: 'https://www.pingodoce.pt/wp-content/uploads/2016/12/arroz-de-pato.jpeg',
      description: 'A traditional Portuguese rice dish with flavorful duck and sausage.',
      servings: 4,
      defaultServings: 4,
      ingredients: [
        Ingredient(name: 'Duck meat', baseQuantity: 600, unit: 'grams'),
        Ingredient(name: 'Rice', baseQuantity: 300, unit: 'grams'),
        Ingredient(name: 'Onions', baseQuantity: 2, unit: 'medium'),
        Ingredient(name: 'Garlic', baseQuantity: 4, unit: 'cloves'),
        Ingredient(name: 'Olive oil', baseQuantity: 2, unit: 'tbsp'),
        Ingredient(name: 'Bay leaves', baseQuantity: 1, unit: 'leaf'),
        Ingredient(name: 'Sausage', baseQuantity: 1, unit: 'piece'),
        Ingredient(name: 'Salt', baseQuantity: 1, unit: 'tsp'),
        Ingredient(name: 'Pepper', baseQuantity: 0.5, unit: 'tsp'),
      ],
      steps: [
        RecipeStep(description: 'Cook the duck meat with bay leaves, salt, and pepper until tender.', timer: 60),
        RecipeStep(description: 'Shred the duck meat and set aside.'),
        RecipeStep(description: 'In a pan, sauté onions and garlic in olive oil.', timer: 5),
        RecipeStep(description: 'Add rice and cook briefly before adding water or broth.'),
        RecipeStep(description: 'Mix in the shredded duck and sausage slices.'),
        RecipeStep(description: 'Bake or simmer until rice is cooked.', timer: 30),
      ],
      comments: [
        Comment(username: 'David', rating: 5, text: 'Authentic and flavorful! Reminds me of my grandma’s cooking.'),
        Comment(username: 'Eva', rating: 4, text: 'Loved it, but a bit too much for just two people.'),
      ],
    ),
    Recipe(
      name: 'Tacos',
      tags: ['Easy', 'Mexican', 'Quick', 'Non-Vegetarian'],
      imageUrl: 'https://static.itdg.com.br/images/640-400/763a97fad5636232d9ffe30955b44acf/347923-original.jpg',
      description: 'A quick Mexican dish with flavorful meat and fresh toppings.',
      servings: 3,
      defaultServings: 3,
      ingredients: [
        Ingredient(name: 'Tortillas', baseQuantity: 6, unit: 'pieces'),
        Ingredient(name: 'Ground beef or chicken', baseQuantity: 200, unit: 'grams'),
        Ingredient(name: 'Lettuce', baseQuantity: 6, unit: 'leaves'),
        Ingredient(name: 'Tomato', baseQuantity: 2, unit: 'medium'),
        Ingredient(name: 'Cheese', baseQuantity: 100, unit: 'grams'),
        Ingredient(name: 'Sour cream', baseQuantity: 3, unit: 'tbsp'),
        Ingredient(name: 'Salsa', baseQuantity: 3, unit: 'tbsp'),
      ],
      steps: [
        RecipeStep(description: 'Cook the meat in a skillet until fully cooked.', timer: 8),
        RecipeStep(description: 'Warm the tortillas in a pan.', timer: 2),
        RecipeStep(description: 'Assemble the tacos with meat, lettuce, tomato, cheese, and toppings.'),
        RecipeStep(description: 'Serve with sour cream and salsa.'),
      ],
      comments: [
        Comment(username: 'Frank', rating: 4, text: 'Simple and tasty, perfect for a quick meal!'),
        Comment(username: 'Grace', rating: 3, text: 'Good, but I prefer chicken over beef for tacos.'),
      ],
    ),
    Recipe(
      name: 'Sushi',
      tags: ['Hard', 'Japanese', 'Non-Cook', 'Seafood'],
      imageUrl: 'https://newinsetubal.nit.pt/wp-content/uploads/2021/02/966dfd70677956dbff0f8f1ee297dccf-754x394.jpg',
      description: 'A delicate Japanese dish featuring vinegared rice and raw fish.',
      servings: 4,
      defaultServings: 4,
      ingredients: [
        Ingredient(name: 'Sushi rice', baseQuantity: 300, unit: 'grams'),
        Ingredient(name: 'Rice vinegar', baseQuantity: 4, unit: 'tbsp'),
        Ingredient(name: 'Nori (seaweed sheets)', baseQuantity: 4, unit: 'pieces'),
        Ingredient(name: 'Raw fish (e.g., salmon, tuna)', baseQuantity: 200, unit: 'grams'),
        Ingredient(name: 'Cucumber', baseQuantity: 4, unit: 'sticks'),
        Ingredient(name: 'Avocado', baseQuantity: 2, unit: 'halves'),
        Ingredient(name: 'Soy sauce', baseQuantity: 3, unit: 'tbsp'),
        Ingredient(name: 'Wasabi', baseQuantity: 1, unit: 'tsp'),
      ],
      steps: [
        RecipeStep(description: 'Rinse and cook sushi rice according to instructions.', timer: 20),
        RecipeStep(description: 'Mix cooked rice with rice vinegar.'),
        RecipeStep(description: 'Place nori on a bamboo mat and spread rice over it.'),
        RecipeStep(description: 'Add fish and vegetables in the center.'),
        RecipeStep(description: 'Roll tightly and slice into pieces.'),
        RecipeStep(description: 'Serve with soy sauce and wasabi.'),
      ],
      comments: [
        Comment(username: 'Hiro', rating: 5, text: 'Amazing sushi recipe, very authentic!'),
        Comment(username: 'Isla', rating: 4, text: 'Took some practice but turned out great.'),
      ],
    ),
    Recipe(
      name: 'Greek Salad',
      tags: ['Easy', 'Greek', 'Vegetarian', 'Gluten-Free', 'Healthy'],
      imageUrl: 'https://img.taste.com.au/tVTiV0Os/w720-h480-cfill-q80/taste/2016/11/super-easy-greek-salad-81664-1.jpeg',
      description: 'A refreshing Greek salad with tomatoes, cucumbers, and feta cheese.',
      servings: 2,
      defaultServings: 2,
      ingredients: [
        Ingredient(name: 'Tomatoes', baseQuantity: 2, unit: 'medium'),
        Ingredient(name: 'Cucumbers', baseQuantity: 1, unit: 'medium'),
        Ingredient(name: 'Red onion', baseQuantity: 1, unit: 'small'),
        Ingredient(name: 'Feta cheese', baseQuantity: 100, unit: 'grams'),
        Ingredient(name: 'Olives', baseQuantity: 3, unit: 'tbsp'),
        Ingredient(name: 'Olive oil', baseQuantity: 2, unit: 'tbsp'),
        Ingredient(name: 'Lemon juice', baseQuantity: 1, unit: 'tbsp'),
        Ingredient(name: 'Salt', baseQuantity: 0.5, unit: 'tsp'),
        Ingredient(name: 'Oregano', baseQuantity: 0.5, unit: 'tsp'),
      ],
      steps: [
        RecipeStep(description: 'Chop tomatoes, cucumbers, and red onion.'),
        RecipeStep(description: 'Crumble feta cheese and add to the bowl.'),
        RecipeStep(description: 'Add olives, olive oil, lemon juice, salt, and oregano.'),
        RecipeStep(description: 'Toss and serve chilled.'),
      ],
      comments: [
        Comment(username: 'Jack', rating: 5, text: 'Perfect summer salad, so fresh and tasty!'),
        Comment(username: 'Kathy', rating: 4, text: 'Loved it, but added a bit more feta.'),
      ],
    ),
    Recipe(
      name: 'Butter Chicken',
      tags: ['Medium', 'Indian', 'Non-Vegetarian', 'Spicy'],
      imageUrl: 'https://saltedmint.com/wp-content/uploads/2024/01/Authentic-Indian-Butter-Chicken-recipe.jpg',
      description: 'A creamy and mildly spiced Indian curry with tender chicken pieces.',
      servings: 4,
      defaultServings: 4,
      ingredients: [
        Ingredient(name: 'Chicken breast', baseQuantity: 500, unit: 'grams'),
        Ingredient(name: 'Butter', baseQuantity: 2, unit: 'tbsp'),
        Ingredient(name: 'Cream', baseQuantity: 100, unit: 'ml'),
        Ingredient(name: 'Tomato puree', baseQuantity: 200, unit: 'ml'),
        Ingredient(name: 'Garlic', baseQuantity: 3, unit: 'cloves'),
        Ingredient(name: 'Ginger', baseQuantity: 1, unit: 'tbsp'),
        Ingredient(name: 'Spices (turmeric, cumin, coriander)', baseQuantity: 1, unit: 'tbsp'),
        Ingredient(name: 'Salt', baseQuantity: 1, unit: 'tsp'),
      ],
      steps: [
        RecipeStep(description: 'Marinate the chicken with spices and salt.', timer: 30),
        RecipeStep(description: 'Cook the marinated chicken until fully cooked.', timer: 10),
        RecipeStep(description: 'Melt butter in a pan and add garlic and ginger.', timer: 2),
        RecipeStep(description: 'Add tomato puree and cook until thickened.', timer: 8),
        RecipeStep(description: 'Add cream and simmer.', timer: 5),
        RecipeStep(description: 'Serve with rice or naan.'),
      ],
      comments: [
        Comment(username: 'Liam', rating: 5, text: 'Best butter chicken recipe! Just like in the restaurant.'),
        Comment(username: 'Mia', rating: 4, text: 'Great taste but a bit too rich for me.'),
      ],
    ),
  ];
}
